### ISSUE TITLE
Windows 11 load dll library issue -- Can't find dependent libraries

### ISSUE THREAD

**Issue by Leon406** [GiviMAD/whisper-jni#5]
> Exception in thread "main" java.lang.UnsatisfiedLinkError: D:\userdata\temp\whisper-jni-native143445693398600\libwhisperjni.dll: Can't find dependent libraries
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2389)
	at java.base/java.lang.Runtime.load0(Runtime.java:755)
	at java.base/java.lang.System.load(System.java:1953)
	at me.leon.asr.Whisper2.main(Whisper2.java:29)
Execution failed for task ':Whisper2.main()'.

**Comment by GiviMAD** [comment]
Thank you for raising the issue.

I forgot to link the library statically to avoid requiring mingw installed.

Seems to be solved for me using the last revision 1.4.2-6.

Let me know if it's solved for you.

BR

**Comment by Leon406** [comment]
fixed
